---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kuadra-kuadrant-io-v1-awsaccount
  failurePolicy: Fail
  name: mawsaccount.kb.io
  rules:
  - apiGroups:
    - kuadra.kuadrant.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsaccounts
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kuadra-kuadrant-io-v1-awsaccount
  failurePolicy: Fail
  name: vawsaccount.kb.io
  rules:
  - apiGroups:
    - kuadra.kuadrant.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsaccounts
  sideEffects: None
