# permissions for end users to edit awsaccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: awsaccount-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kuadra
    app.kubernetes.io/part-of: kuadra
    app.kubernetes.io/managed-by: kustomize
  name: awsaccount-editor-role
rules:
- apiGroups:
  - kuadra.kuadra.kuadrant.io
  resources:
  - awsaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuadra.kuadra.kuadrant.io
  resources:
  - awsaccounts/status
  verbs:
  - get
