---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kuadra.kuadrant.io
  resources:
  - awsaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuadra.kuadrant.io
  resources:
  - awsaccounts/finalizers
  verbs:
  - update
- apiGroups:
  - kuadra.kuadrant.io
  resources:
  - awsaccounts/status
  verbs:
  - get
  - patch
  - update
