apiVersion: kuadra.kuadrant.io/v1
kind: User
metadata:
  labels:
    app.kubernetes.io/name: user
    app.kubernetes.io/instance: user-sample
    app.kubernetes.io/part-of: kuadra
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kuadra
  name: user-sample
spec:
  awsAccount:
    spec:
      user:
        userName: ib-dns
        groups:
          - dns-management
        zones:
          - ib.kuardra.io
